"""
codegen.py  --  Stage 3: bundle the parsed IR with the runtime engine into app.py.

Usage:  python codegen.py workbook_ir.json -o app.py
The generated app.py embeds the IR and calls engine.run(IR); engine.py renders
every dashboard/sheet generically. Deploy app.py + engine.py + backend.py +
config.py + calc_translator.py together.
"""

import argparse
import ast
import json


def build(ir):
    """Bundle the IR into runnable app source.

    The IR is embedded via repr() of the JSON text, NOT a raw triple-quoted
    literal. Any workbook value can legally contain a quote or backslash --
    a group over Product Name yields SQL like IN ('Belkin ... 6''') whose
    doubled apostrophe + closing quote spells ''' and silently TERMINATED the
    r'''...''' wrapper mid-blob, so the rest of the IR parsed as code and the
    generated app died with SyntaxError before rendering anything. repr() is
    the only embedding that is correct for every possible payload.
    """
    blob = json.dumps(ir, indent=2)
    src = (
        "# GENERATED by codegen.py -- do not hand-edit; regenerate from the .twb.\n"
        "# Tableau workbook -> Streamlit (local DuckDB / Snowflake Snowpark).\n"
        "import json\n"
        "from engine import run\n\n"
        "IR = json.loads(" + repr(blob) + ")\n\n"
        "run(IR)\n"
    )
    # Never emit a file that cannot parse: codegen is the one stage that is
    # supposed to be deterministic, so it must prove it rather than assume it.
    try:
        ast.parse(src)
    except SyntaxError as e:
        raise RuntimeError(
            f"codegen produced unparsable source at line {e.lineno}: {e.msg}. "
            "This is a codegen bug -- the IR is data and must never be able to "
            "break the generated file's syntax."
        ) from e
    if json.loads(ast.literal_eval(src.split("json.loads(", 1)[1]
                                   .rsplit(")\n\nrun(IR)", 1)[0])) != ir:
        raise RuntimeError("codegen round-trip mismatch: embedded IR != source IR")
    return src


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("ir")
    ap.add_argument("-o", "--out", default="app.py")
    a = ap.parse_args()
    ir = json.load(open(a.ir))
    open(a.out, "w").write(build(ir))
    n = sum(len(d["sheets"]) for d in ir["dashboards"])
    print(f"Generated {a.out}: {len(ir['dashboards'])} dashboards, {n} sheets")


if __name__ == "__main__":
    main()
