-- cortex_check.sql -- run ONCE in Snowsight (account wb19670-c2gpartners,
-- connection 'wbr') to inventory which Cortex AI surfaces this account/region
-- actually has, BEFORE building against them. Paste results back to the
-- accelerator session; each section is independent -- a failure in one does
-- not block the rest.

-- 1. Which Cortex functions exist in this region?
SHOW FUNCTIONS IN SCHEMA SNOWFLAKE.CORTEX;

-- 2. LLM inference works + which models? (tiny prompt = negligible cost)
SELECT SNOWFLAKE.CORTEX.COMPLETE('claude-3-5-sonnet', 'Reply with the single word: ok') AS claude_ok;
SELECT SNOWFLAKE.CORTEX.COMPLETE('mistral-large2',    'Reply with the single word: ok') AS mistral_ok;

-- 3. AISQL family present? (newer AI_ prefixed functions)
SELECT AI_COMPLETE('claude-3-5-sonnet', 'Reply with the single word: ok') AS aisql_ok;

-- 4. Cortex Analyst: needs a semantic model on a stage. Create the stage the
--    accelerator will publish generated models to (idempotent).
CREATE STAGE IF NOT EXISTS WBR_DB.PUBLIC.TABLEAU_TO_SIS_SEMANTIC
  DIRECTORY = (ENABLE = TRUE) COMMENT = 'Cortex Analyst semantic models generated by cortex_semantic.py';
-- then upload (from a local terminal with snow CLI, connection wbr):
--   snow stage copy "sql/cortex/superstore_semantic_model.yaml" @WBR_DB.PUBLIC.TABLEAU_TO_SIS_SEMANTIC --connection wbr
--   snow stage copy "sql/cortex/e_commerce_software_sales_dashboard_votd_semantic_model.yaml" @WBR_DB.PUBLIC.TABLEAU_TO_SIS_SEMANTIC --connection wbr
LIST @WBR_DB.PUBLIC.TABLEAU_TO_SIS_SEMANTIC;

-- 5. Cortex Search service creation privilege? (only needed for RAG later --
--    skip if it errors, not required for the Analyst chat tab)
SHOW CORTEX SEARCH SERVICES IN DATABASE WBR_DB;

-- 6. Semantic views supported? (SQL-native alternative to stage-hosted YAML)
SHOW SEMANTIC VIEWS IN SCHEMA WBR_DB.PUBLIC;

-- 7. What has Cortex cost so far this month? (director will ask)
SELECT SERVICE_TYPE, SUM(CREDITS_USED) AS CREDITS
FROM SNOWFLAKE.ACCOUNT_USAGE.METERING_DAILY_HISTORY
WHERE USAGE_DATE >= DATE_TRUNC('MONTH', CURRENT_DATE)
GROUP BY 1 ORDER BY 2 DESC;
