-- Sample - Superstore: 'Orders' has no physical column (ORDERS) -- skipped.
-- Sample - Superstore: 'Orders' has no physical column (ORDERS) -- skipped.
-- Sample - Superstore: 'Sales above Target?' has no physical column (CALCULATION_9951107165644870) -- skipped.
CREATE OR REPLACE SEMANTIC VIEW WBR_DB.PUBLIC.R1_TEST_UPLOAD_SUPERSTORE_SEMANTIC
  TABLES (
    SALES_COMMISSION AS WBR_DB.PIPELINE_DEMO.SALES_COMMISSION
      WITH SYNONYMS = ('Sales Commission')
      COMMENT = 'Migrated from Tableau datasource: Sales Commission',
    SAMPLE_SUPERSTORE AS WBR_DB.PIPELINE_DEMO.SAMPLE_SUPERSTORE
      WITH SYNONYMS = ('Sample - Superstore')
      COMMENT = 'Migrated from Tableau datasource: Sample - Superstore'
  )
  FACTS (
    SALES_COMMISSION.SALES AS SALES WITH SYNONYMS = ('Sales'),
    SAMPLE_SUPERSTORE.DISCOUNT AS DISCOUNT WITH SYNONYMS = ('Discount'),
    SAMPLE_SUPERSTORE.PROFIT AS PROFIT WITH SYNONYMS = ('Profit'),
    SAMPLE_SUPERSTORE.QUANTITY AS QUANTITY WITH SYNONYMS = ('Quantity'),
    SAMPLE_SUPERSTORE.SALES AS SALES WITH SYNONYMS = ('Sales')
  )
  DIMENSIONS (
    SALES_COMMISSION.SALES_PERSON AS SALES_PERSON WITH SYNONYMS = ('Sales Person'),
    SAMPLE_SUPERSTORE.CATEGORY AS CATEGORY WITH SYNONYMS = ('Category'),
    SAMPLE_SUPERSTORE.CITY AS CITY WITH SYNONYMS = ('City'),
    SAMPLE_SUPERSTORE.CUSTOMER_NAME AS CUSTOMER_NAME WITH SYNONYMS = ('Customer Name'),
    SAMPLE_SUPERSTORE.ORDER_DATE AS ORDER_DATE WITH SYNONYMS = ('Order Date'),
    SAMPLE_SUPERSTORE.PRODUCT_NAME AS PRODUCT_NAME WITH SYNONYMS = ('Product Name'),
    SAMPLE_SUPERSTORE.SEGMENT AS SEGMENT WITH SYNONYMS = ('Segment'),
    SAMPLE_SUPERSTORE.SUB_CATEGORY AS SUB_CATEGORY WITH SYNONYMS = ('Sub-Category')
  )
  METRICS (
    SALES_COMMISSION.ACHIEVED_QUOTA AS CASE WHEN SUM((SALES)) >= 500000.0 THEN '100% +' WHEN SUM((SALES)) >= 0.75 * 500000.0 THEN '75-100%' WHEN SUM((SALES)) >= 0.5 * 500000.0 THEN '50-75%' ELSE 'Below 50%' END
      WITH SYNONYMS = ('Achieved Quota', 'Achievement (variable) (copy)')
      COMMENT = 'Tableau calculated field: Achieved Quota',
    SALES_COMMISSION.OF_QUOTA_ACHIEVED AS AVG((SALES))/500000.0
      WITH SYNONYMS = ('% of quota achieved', 'Calculation_0440925131659539')
      COMMENT = 'Tableau calculated field: % of quota achieved',
    SALES_COMMISSION.SORT_BY_FIELD AS CASE WHEN 'Names'='Names' THEN 0 WHEN 'Names'='% quota descending' THEN -(AVG((SALES))/500000.0) ELSE (AVG((SALES))/500000.0) END
      WITH SYNONYMS = ('Sort by field', 'Calculation_8140925133029303')
      COMMENT = 'Tableau calculated field: Sort by field',
    SALES_COMMISSION.TOTAL_COMPENSATION AS MIN((50000.0)) + SUM(((18.4*SALES)/100))
      WITH SYNONYMS = ('Total Compensation')
      COMMENT = 'Tableau calculated field: Total Compensation',
    SALES_COMMISSION.SUM_SALES_SUM_SALES_FORECAST AS SUM(SALES)-SUM((SALES*(1-0.064)*(1+0.6)))
      WITH SYNONYMS = ('SUM([Sales])-SUM([Sales Forecast])', 'Calculation_9330126204734562')
      COMMENT = 'Tableau calculated field: SUM([Sales])-SUM([Sales Forecast])',
    SAMPLE_SUPERSTORE.SALES_PER_CUSTOMER AS Sum(SALES)/ NULLIF(COUNT(DISTINCT CUSTOMER_NAME), 0)
      WITH SYNONYMS = ('Sales per Customer', 'Calculation_9321103144526191')
      COMMENT = 'Tableau calculated field: Sales per Customer',
    SAMPLE_SUPERSTORE.PROFIT_RATIO AS sum(PROFIT)/ NULLIF(sum(SALES), 0)
      WITH SYNONYMS = ('Profit Ratio', 'Calculation_9921103144103743')
      COMMENT = 'Tableau calculated field: Profit Ratio',
    SAMPLE_SUPERSTORE.PROFIT_PER_ORDER AS Sum(PROFIT)/ NULLIF(COUNT(DISTINCT ORDER_ID), 0)
      WITH SYNONYMS = ('Profit per Order', 'Sales per Customer (copy)')
      COMMENT = 'Tableau calculated field: Profit per Order'
  )
  COMMENT = 'Generated by cortex_semantic.py from C:\Users\SHARAT~1\AppData\Local\Temp\twbconv_qovco7l8\R1_Test_Upload_-_Superstore.twbx';
-- metric SKIPPED (window function -- not a scalar metric): Order Profitable?
-- metric SKIPPED (window function -- not a scalar metric): Calculation_9060122104947471
