-- GENERATED by semantic_layer.py -- views materialize the
-- workbook's OWN relationship graph; the app queries these
-- views directly (columns aliased to its physical naming).

CREATE OR REPLACE VIEW SUPERSTORE.PUBLIC.CUSTOMERS_DATADNA_DATASET_CHALLENGE_E_COMMERCE_DATASET_NOVEMBER_2025_MODEL AS
SELECT
  f."event_id" AS EVENT_ID,
  f."event_type" AS EVENT_TYPE,
  f."event_date" AS EVENT_DATE,
  f."customer_id" AS CUSTOMER_ID,
  f."product_id" AS PRODUCT_ID,
  f."country" AS COUNTRY,
  f."latitude" AS LATITUDE,
  f."longitude" AS LONGITUDE,
  f."region" AS REGION,
  f."channel" AS CHANNEL,
  f."payment_method" AS PAYMENT_METHOD,
  f."currency" AS CURRENCY,
  f."quantity" AS QUANTITY,
  f."unit_price_local" AS UNIT_PRICE_LOCAL,
  f."discount_code" AS DISCOUNT_CODE,
  f."discount_local" AS DISCOUNT_LOCAL,
  f."tax_local" AS TAX_LOCAL,
  f."net_revenue_local" AS NET_REVENUE_LOCAL,
  f."fx_rate_to_usd" AS FX_RATE_TO_USD,
  f."net_revenue_usd" AS NET_REVENUE_USD,
  f."is_refunded" AS IS_REFUNDED,
  f."refund_datetime" AS REFUND_DATETIME,
  f."refund_reason" AS REFUND_REASON,
  d0."customer_id" AS CUSTOMER_ID_CUSTOMERS,
  d0."signup_date" AS SIGNUP_DATE,
  d0."region" AS REGION_CUSTOMERS,
  d0."currency_preference" AS CURRENCY_PREFERENCE,
  d0."segment" AS SEGMENT,
  d0."acquisition_channel" AS ACQUISITION_CHANNEL,
  d0."age_band" AS AGE_BAND,
  d0."country" AS COUNTRY_CUSTOMERS,
  d0."country_latitude" AS COUNTRY_LATITUDE,
  d0."country_longitude" AS COUNTRY_LONGITUDE,
  d1."product_id" AS PRODUCT_ID_PRODUCTS,
  d1."product_name" AS PRODUCT_NAME,
  d1."category" AS CATEGORY,
  d1."is_subscription" AS IS_SUBSCRIPTION,
  d1."billing_cycle" AS BILLING_CYCLE,
  d1."base_price_usd" AS BASE_PRICE_USD,
  d1."first_release_date" AS FIRST_RELEASE_DATE,
  d1."vendor" AS VENDOR,
  d1."resale_model" AS RESALE_MODEL,
  d1."brand_safe_name" AS BRAND_SAFE_NAME,
  d1."product_name_orig" AS PRODUCT_NAME_ORIG,
  d1."base_price_usd_orig" AS BASE_PRICE_USD_ORIG,
  d1."base_key" AS BASE_KEY,
  d1."product_version" AS PRODUCT_VERSION
FROM SUPERSTORE.PUBLIC.EVENTS f
LEFT JOIN SUPERSTORE.PUBLIC.CUSTOMERS d0 ON f."customer_id" = d0."customer_id"
LEFT JOIN SUPERSTORE.PUBLIC.PRODUCTS d1 ON f."product_id" = d1."product_id"
;

